Uberspace/lab

- LICENSE
- README.md
- source/_templates/footer.html
> add license

- source/_templates/breadcrumbs.html
- source/conf.py
> :bug: change references to "Manual" to "Lab"

- .gitlab-ci.yml
Merge after #7 and #24.
Closes #26.
> make master our production branch

- source/guide_gitea.rst
Added the creation of the config folder
> Updated guide_gitea.rst 

- source/guide_gitea.rst
added generation of the gitea database
according to #39
> updated source/guide_gitea.rst

- source/guide_ghost.rst
> :lipstick: add "tested with" to Ghost

- source/guide_etherpad.rst
reworked the contribution to adjust it to the suggestions and new requirements
> adding etherpad guide (second try)

- source/guide_jingo.rst
I don't know if you have any relevance guidelines for tools. This one is a not very much known but still used by some people according to the forks and stars on [Github](https://github.com/claudioc/jingo), I personally like to use it because of its simplicity.
> guide for jingo wiki

- source/guide_etherpad.rst
- source/guide_ghost.rst
- source/guide_gitea.rst
- source/guide_jingo.rst
- source/guide_lychee.rst
- source/guide_minim.rst
- source/guide_wordpress.rst
> Add contributors

- source/guide_wordpress.rst
> :memo: rework wordpress with wp-cli

- source/guide_gitea.rst
> :bug: fix domains link

- source/guide_lychee.rst
Pulling from Github can be done simpler. Also added security improvements to hide the .git folders.
> Lychee improvement

- source/guide_wallabag.rst
This is a guide how to install the Wallabag server side application.
> guide for Wallabag

- source/guide_etherpad.rst
> :wrench: NODE_ENV=production

- source/guide_wallabag.rst
> add @ezzra as wallbag author

- source/guide_gitea.rst
> add tested versions to gitea

- source/_templates/layout.html
> :sparkles: link to github feed

- source/guide_neos.rst
Warning added regarding incompatibility between Uberspace and Neos v4. 
Currently the setup fails because the table can't be created as expected by the assistant.
> Warning inserted

- source/guide_ghost.rst
Added missing dash to --no-setup-linux-user argument
> Fixed --no-setup-linux-user argument

- source/guide_nextcloud.rst
The cronjob was started all minute and nextcloud say all 15 minutes so i changed.
> Nextcloud says all 15 minutes

- STYLE.md
It seems that some occurences of usernames have been missed when they were changed to "isabell".
> Use "isabell" as username in styleguide examples

- source/_static/js/custom.js
Include non-ascii letters in author matching regex, see https://github.com/Uberspace/lab/issues/169
> :art: add umlauts to author regex

- source/guide_lychee.rst
fixed links because lychee repo moved to organisation
> lychee - fixed links for new lychee organisation

- source/_static/images/freshrss.svg
- source/guide_freshrss.rst
> :pencil2: guide for FreshRSS

- source/_static/images/kanboard.svg
- source/guide_kanboard.rst
> Add Kanboard guide

- source/guide_etherpad.rst
> Use tag instead of release branch for Etherpad update

- source/guide_gitlab-runner.rst
unified usage of paths to binary files
btw: thanks for the guide, @bytekeks! 🙂
> fix(guide-gitlab-runner): update binary paths

- source/guide_matomo.rst
i am not sure if using `/usr/bin/php71`hardcoded is a good choice.
> [matomo] add auto-archiving option

- source/guide_neos.rst
> Update Neos guide to use version 4.1

- source/_static/images/bookstack.svg
- source/guide_bookstack.rst
Closes #209 
Please note that BookStack needs Uberspace 7.1.15 with the updated MariaDB. I successfully tested it on kopff already.
> Add guide for BookStack

- source/guide_seafile.rst
Re-sort port find to Prerequisites
Add redirect for tmp_cache; Avoid conflict with other users on server
> Re-sort port find to Prerequisites; Add redirect for tmp_cache

- source/guide_akaunting.rst
- source/guide_bookstack.rst
- source/guide_codimd.rst
- source/guide_grav.rst
- source/guide_ioncube.rst
- source/guide_limesurvey.rst
- source/guide_postgresql.rst
- source/guide_satis.rst
- source/guide_selfoss.rst
- source/guide_the-lounge.rst
- source/hall_of_fame.rst
when building the html the first time. a lot of warnings are beeing displayed. this should fix quite a few.
> [general] fix warnings

- source/_static/images/radicale.svg
- source/guide_radicale.rst
i will test the PR tomorrow. Maybe it works already.
Please leave feedback to it.
> [radicale] add guide

- source/guide_codimd.rst
> [codimd] fix mysql charset utf8mb4

- source/guide_etherpad.rst
Currently the personalization part is quite short. I added information regarding the use of css-files for customization.
> Information about customization added

- source/guide_autossh.rst
> Add guide for autossh

- source/guide_postgresql.rst
I solved small wording mistakes and placed the focus on an example (synapse) as data base name (line 351 and 358) instead to use the user name during the data base creation process to avoid misunderstandings.
Best regards
FM
> PostgreSQL guide update

- source/guide_wallabag.rst
Before changes in parameters.yml are active, you have to clear your cache.
> added `clear cache for changes in parameters.yml`

- source/guide_mongodb.rst
> Always end your console code blocks with [isabell@stardust ~]$
> MongoDB style

- source/guide_autossh.rst
- source/guide_buildbot.rst
- source/guide_embetty.rst
- source/guide_miniflux.rst
- source/guide_mongodb.rst
- source/guide_pretix.rst
- source/guide_prometheus.rst
- source/guide_radicale.rst
- source/guide_redis.rst
- source/guide_resilio.rst
- source/guide_the-lounge.rst
- source/includes/install-uwsgi.rst
> :memo: remove hardcoded binary paths #294

- source/guide_codimd.rst
> update CodiMD reference to new Github org

- STYLE.md
> add description for commit messages to style-guide

- source/guide_mailman-3.rst
> [mailman3] add misssing .qmail configuration

- source/guide_hugo.rst
Step 3 describes how to create a new page. The reference to step 2 would be correct.
> fixed wrong step unter Updates

- source/guide_codimd.rst
- source/guide_gitea.rst
- source/guide_hugo.rst
- source/guide_radicale.rst
> :bug: make relative author links absolute

- source/guide_django.rst
> Fixed typos

- STYLE.md
> fix broken link

- STYLE.md
- source/guide_mosh.rst
I just opened the issue #405. In it I requested my wish for Mosh guide and that I would like to write one. 
So did I. I tried to stick with your guidelines.
> [Mosh] add guide for Mosh

- source/guide_znc.rst
https://github.com/Uberspace/lab/issues/183
> [ZNC] add guide for ZNC

- source/guide_znc.rst
> [ZNC] use the same port as in includes/open-port.rst

- source/guide_postgresql.rst
added a minor clarification to the latest comment on #241
> added minor clarification

- source/includes/supervisord.rst
an idea for a snippet like #414
> initial try for an example

- source/guide_gitlab-runner.rst
remove the version from the line in gitlab-runner.sh , as discussed in #433
> remove the version from the line in gitlab-runner.sh #433

- source/guide_gitlab-runner.rst
GitLab Runner: gitlab-runner.ini does not accept $USER #437
> GitLab Runner: gitlab-runner.ini does not accept $USER

- source/guide_codimd.rst
Known issue: One should try to improve the part about removing `UglifyJS`. This is related to #361.
> [CodiMD] Make installation work for the latest release v1.4.0

- source/guide_guillotine.rst
This adds a Guide for @technoweenie's [Guillotine](https://github.com/technoweenie/guillotine).
From my [guide](https://deploy-preview-456--uberlab.netlify.com/guide_guillotine.html):
> Guillotine is a simple URL Shortener written in Ruby and powers GitHubs URL Shortener [Git.io](https://Git.io).
It supports multiple storage adapters, including MySQL, PostgreSQL, SQLite, Redis, Riak and Cassandra.
> Guide for Guillotine

- source/guide_hugo.rst
Changes with this PR:
- Updated version of Hugo
- Set the `HUGO_CACHEDIR`, so that the build will succeed
> Update the Hugo guide

- source/guide_ezmlm.rst
Inform the user about issue when testing the new created mailing list with gmail addresses
> Add Gmail hint

- source/guide_php-fusion.rst
> Fix PHP-Fusion links

- source/guide_gitlab-runner.rst
Use Git**L**ab with capital L everywhere.
> Use GitLab everywhere

- source/guide_alertmanager.rst
Hi,
alertmanager is a companion of prometheus to send out alerts. I'm using it for a couple of months now and thought it might be helpful for other people as well.
Malte
> Guide for alertmanager

- source/guide_mailman-3.rst
Fix a few typos and add a note about outdated SQLite versions.
> Improve Mailman 3 instructions

- source/guide_humhub.rst
> [HumHub] add new guide humhub

- source/guide_mailman-3.rst
the package's name was incorrect
> Correct package name

- source/guide_jekyll.rst
> [jekyll] Add --force when creating website project in existing bare repository

- source/guide_nextcloud.rst
> Nextcloud guide: Added hint on choosing the data direcory's location

- source/guide_django.rst
> [django] :pencil2: fix curl URL

- source/guide_nextcloud.rst
Just a very very small change. This way it matches the default settings from https://github.com/Uberspace/lab/blob/master/source/includes/my-print-defaults.rst.
> Update db pw to match the default one

- source/guide_radicale.rst
There is a radicale too much in `python3 -m pip install --user --upgrade radicale radicale bcrypt passlib`
> remove one radicale

- source/guide_ghost.rst
> Update ghost guide

- source/guide_drupal.rst
* Made file edit statements more generic
* Small improvement and fixes
* Complete rework of drush section
** Switched from drush-launcher to drush
** Added configuration subsections
> [drupal] Minor changes + rework of drush section

- source/guide_aptly.rst
Closes #368.
I didn't add a logo for now because I'm not sure if I can just copy it for this guide (copyright etc.).
> Add guide for aptly

- source/guide_sharex.rst
Small enhancements to my guide ;D
> [ShareX] Added menuselection.

- source/guide_mailman-3.rst
See https://github.com/Uberspace/lab/issues/535#issuecomment-573645274
> Switch postorius and hyperkitty to prevent Django3

- source/guide_nextcloud.rst
Added (a now corrected) instruction for installing Onlyoffice in Nextcloud
> Update guide_nextcloud.rst (Onlyoffice)

- source/guide_nextcloud.rst
added some tweaks reformatted the guide a bit
> [nextcloud] update guide for NC 18.02

- source/_static/images/roundcube.svg
- source/guide_roundcube.rst
Hi, i've added a guide for [Roundcube](https://roundcube.net/).
closes#593
> [roundcube] add guide for roundcube

- source/guide_flatboard.rst
- source/guide_gotify.rst
- source/guide_grav.rst
- source/guide_gsales2.rst
- source/guide_jekyll.rst
- source/guide_kimai.rst
- source/guide_mattermost.rst
- source/guide_nextcloud.rst
- source/guide_redis.rst
- source/guide_redmine.rst
- source/guide_rocketchat.rst
- source/guide_simpleid.rst
- source/guide_syncthing.rst
- source/guide_taskd.rst
- source/guide_teamspeak.rst
- source/guide_up1.rst
- source/guide_wallabag.rst
After improving the dict for lab-specific words, these issues remained. With the better dict no only 10 spelling errors (German words in a tutorial, false negative) remain.
PR for spellchecking follows.
> Fix some more typos

- source/guide_drupal.rst
Fixes #588.
I've removed the sections on Drush to ensure a straight forward sequence of steps.
> [drupal] Rework Drupal guide

- source/guide_roundcube.rst
"Your" is possessive, "you're" is a contraction of "you are".  Should be "you're" here, as in "you are done".
> Minor grammatical fix in guide_roundcube

- README.md
i found this in the official manual README, could be helpful for the community in the progress of writing guides :sparkles:
> add sphinx autobuild to README

- source/guide_ghost.rst
> [ghost] replace npm with yarn in upgrade to fix timezone issues

- source/guide_mailman.rst
> install dnspython; make commands more copypastable

- source/guide_fathom_lite.rst
Finally, after over a year, add the proposed guide for Fathom Lite (previously named Fathom).
closes Uberspace/lab#342
> Add guide for Fathom Lite 

- source/guide_pretix.rst
configuration changed to make webauthn work behind the reverseproxy
> Update pretix configuration

- source/guide_wiki-js.rst
Changing gitreleases.dev path to latest github URL.
> Fixing update script

- source/guide_typo3-cms.rst
Changes include:
- Updated composer commands
- Updated installation instructions for step 4 (new field 'email')
- Updated author email (not guide related, but necessary anyways)
Resolves: #628
> [TASK] Update TYPO3 CMS guide for version 10.4

- source/guide_wallabag.rst
> add PHP 7.4 warning #658

- source/guide_cryptpad.rst
> 3 sind Bremer Recht.
Finally a mergeable PR for my small updates regarding the Cryptpad guide.
Resolves #646 and #643
> [Cryptpad] Update guide

- source/guide_wkd.rst
> [WKD] Add guide for Web Key Directory

- source/guide_prometheus.rst
> fix [prometheus] url

- source/guide_mattermost.rst
based on step 7 in https://docs.mattermost.com/administration/upgrade.html
> add additional paths for mattermost upgrade

- source/guide_gollum.rst
> [gollum] fix headline build warning

- STYLE.md
To prevent contributors copy-paste the boilerplate with redundant content I give an example and set includes in the boilerplate.
> [STYLE.md] explain includes and update boilerplate

- source/guide_ethercalc.rst
- source/guide_isso.rst
again a suggestion to fix the build warnings I got when building the lab local.
> [ethercalc] [isso] fix building warning

- source/_static/images/etesync.svg
- source/guide_etesync-server.rst
New guide for EteSync.
closes #710
> [etesync-server] add guide for EteSync Server

- source/guide_nextcloud.rst
Oops, something was missing. Hopefully nobody else noticed :smile:
> [nextcloud] fix scan command

- source/_static/images/prosody.svg
- source/guide_prosody.rst
Prosody is a modern XMPP communication server. It aims to be easy to set up and configure, and efficient with system resources. Additionally, for developers it aims to be easy to extend and give a flexible system on which to rapidly develop added functionality, or prototype new protocols.
I tried to make a more easier guide in the hope to bring prosody into the lab requested in #107 
I used some parts 1:1 of the rejected guide by fapsi. I dont know how to handle it with the credits (maybe mark as co author?)
> [prosody] add guide for prosody

- source/guide_pixelfed.rst
- source/guide_pleroma.rst
[Pleroma]
Add tag ``fediverse``
Fixed some typos
Remove Redis part with a note
Add note for horizon service
Updated update part
[pleroma]
Add tag ``fediverse``
Add update page note
> [pixelfed] [pleroma] small updates

- source/guide_prosody.rst
Add certificate generation for ``conference.isabell.org``
> [prosody] fix muc certificate issue

- source/guide_postgresql.rst
I updated the document to use the current version (12.4) of PostgreSQL. This uses another auth method and also the output of the initdb changed a bit.
> Update to PostgreSQL 12.4

- source/guide_grocy.rst
While applying suggested changes in the original PR, I messed up some paths. This should fix them.
> [Grocy] Fix paths and some steps.

- source/guide_postgresql.rst
Mostly rewording.
A small add for unix domain sockets.
> [postgres] guide improvements.

- source/_static/css/custom.css
> fix for 404 error in css

- source/guide_mailman-3.rst
completing the PR #766 with uwsgi temporary fix
> Mailman3 fix

- source/guide_offen.rst
you need to suppress x-frame-options to use offen correctly
> offen guide changed

- source/guide_ezmlm.rst
add info about
* options 
* adding moderators
* allowing other addresses
* specify language settings
> Append more common useful information

- source/_static/css/custom.css
same as https://github.com/Uberspace/manual/pull/213
> remove css paddings in highlighting

- source/guide_nextcloud.rst
> [nextcloud] disable php output buffer as requirement for NC20

- source/guide_joomla.rst
PHP 7.1 is EOL. The latest version works also with 7.4
> Update Joomla Version in Guide

- source/guide_bitwarden.rst
- source/guide_code-server.rst
- source/guide_coturn.rst
- source/guide_cryptpad.rst
- source/guide_drupal.rst
- source/guide_ejabberd.rst
- source/guide_etesync-server.rst
- source/guide_fathom_lite.rst
- source/guide_gitea.rst
- source/guide_hasteserver.rst
- source/guide_isso.rst
- source/guide_jupyter-notebook.rst
- source/guide_lychee.rst
- source/guide_moodle.rst
- source/guide_pixelfed.rst
- source/guide_pleroma.rst
- source/guide_postgresql.rst
- source/guide_processwire.rst
- source/guide_prosody.rst
- source/guide_redis.rst
- source/guide_redmine.rst
- source/guide_shellinabox.rst
- source/guide_starship.rst
- source/guide_wkd.rst
I re-ran some spell checking on the lab and corrected some typos.
> Fix typos in guides

- source/guide_taskd.rst
Updated and partly improved the taskd guide as I was installing it for me.
Tried to let it run with the web backends but didn't work; so I kept it with a port.
> Update and improve taskd guide

- source/guide_mongodb.rst
> [mongodb] Updated MongoDB guide

- source/guide_mattermost.rst
> [Mattermost] Fix guide, change data directory path

- source/_static/images/teamcity.svg
- source/guide_teamcity.rst
Added the guide for TeamCity
closes #828
> [TeamCity] Added guide for TeamCity

- source/guide_flask.rst
> [flask] added config for subpaths

- source/guide_privatebin.rst
> [privatebin] Edited some typos and streamlined the guide

- source/guide_gitlab-runner.rst
> Include updates to gitlab-runner doc, fixes #867

- source/guide_bitwarden.rst
> [bitwarden_rs] Added create data folder instructions & note to web-vault

- source/guide_gitlab-runner.rst
As I had another look on my change, I spotted missing space.
> [GitLab Runner] Add missing space

- source/guide_ghost.rst
> [ghost] skip mysql check

- source/guide_nextcloud.rst
closes #851 
also add new database optimisation command (NC20)
deploy preview: [guide_nextcloud.html#updates](https://deploy-preview-880--uberlab.netlify.app/guide_nextcloud.html#updates)
> [nextcloud] disable backup in update script

- source/guide_ghost.rst
The question "Do you want to start Ghost?" does not show up at the console (and we already use the '--no-start' parameter at ghost install) Therefore, we can remove the mentioned line from the doc.
> [ghost] Remove line 'Do you want to start Ghost?: Answer No.'

- source/guide_pleroma.rst
- Add new questions during configuration file generation
- Add postgresql queue timeout
- Add instructions for ExifTool
- Update tested version
fixes #900, fixes #739
> [pleroma] Update guide

- CONTRIBUTING.md
the renaming of master -> main breaks the subscriptions
Maybe there are other references that need updating?
> update feed url

- BROKEN_GUIDES.md
- CONTRIBUTING.md
- source/_templates/layout.html
- source/index.rst
haha, you were faster than me, I had to remove my "github-version" fix
> fix some refs to main branch

- source/guide_mongodb.rst
> [mongodb] update for pre-installed binaries

- source/guide_piwigo.rst
URL did resume in a 404 before
> [piwigo] Fix URL of official website

- source/guide_bitwarden.rst
Node.js 13 is not available anymore. Further i updated the webinterface version and fixed an uncomplete command.
> bitwarden_rs - Updated versions and corrected one Command

- source/guide_nextcloud.rst
hi there, here's a PR for #915 , contributing to the NextCloud guide a bit
> resolve #915: NextCloud guide: add more step info and flesh out descriptions

- source/guide_rocketchat.rst
> [rocket.chat] add startsecs=90

- STYLE.md
> [STYLE.md] Correct spelling, make titles more consistent

- source/guide_ts3audiobot.rst
Added guide for TS3AudioBot
Refer to #940
> Added guide for TS3AudioBot

- source/guide_lychee.rst
lychee repository has been moved from user electerious to an own organization
> Change lychee project website URL

- source/guide_eqdkp-plus.rst
Additonally, added nicer description for creating an additional database
> [EQdkpPlus] Added licence and backup section

- source/guide_nextcloud.rst
> [nextcloud] use PHP 7.4 as recommended

- source/conf.py
> [meta] fix github_version to main

- source/_static/images/openslides.svg
- source/guide_openslides.rst
Initial guide for installation OpenSlides, a free, web-based presentation and assembly system for managing and projecting agenda, motions, and elections of assemblies.
> [OpenSlides ] Added OpenSlides Guide

- source/guide_gollum.rst
https://stackoverflow.com/a/46805870
> [gollum] add hash -r to installation instructions.

- source/guide_umami.rst
* mysql password is not needed on the given operation
* `npm run build-mysql-client` is automatically included in `npm run build`
> Update umami guide

- source/guide_bookstack.rst
> [bookstack] set APP_URL

- source/guide_humhub.rst
updated guide to match currently supported versions.
> [HumHub] check compatibility w/ current versions

- source/guide_kirby.rst
worked just fine, updated the versions presented in the guide.
> [kirby] check compatibility with current versions

- source/guide_icecast2.rst
- source/guide_synapse.rst
- source/guide_writefreely.rst
Corrected chmod command and updated links and contact info.
> Update icecast2 and writefreely guide

- source/guide_pixelfed.rst
* Fix formatting
* Config editing has to take place before key:generate, otherwise it will fail because of the missing redis connection
* Put MySQL Password in Quotes for more compatibility
> Fixes for pixelfed guide

- README.md
- authorship/README.md
- authorship/authorship/__init__.py
- source/_static/js/custom.js
- source/index.rst
best after https://github.com/Uberspace/lab/pull/1068
> add tag list to sidebar nav

- source/_static/css/custom.css
adds scrolling [as suggested](https://github.com/Uberspace/lab/pull/1070), but only for the guides section instead the whole side navigation.
> :lipstick: only show scrollbars for guide section in side nav

- source/guide_ghost.rst
> use Ghost-x.yy.z.zip for updates

- source/guide_nextcloud.rst
An anonymous human mailed me and asked for these changes.
I also enabled a command in the update script since NC19 is EOL
> [Nextcloud] ✏ update database maintenance commands

- source/guide_uu-notify.rst
* be more precise about github personal access token scopes
* fixed a link being relative to the lab, should be absolute --> use protocol prefix `https://`
> [uu-notify] some small corrections [non-functional]

- source/guide_uu-notify.rst
changes:
- added section "Optional"
- writing Gotfiy uppercase where it is a name
> [uu-notify] add optional instructions for app icon

- source/guide_umami.rst
- add missing backtick, so formatting looks correct in the frontend
> fix: add missing backtick

- source/guide_openslides.rst
> [openslides] replace servicectl w/ supervisorctl

- source/guide_flask.rst
I've updated the flask guide, made (few) opinionated changes to make it more readable and addressed open issues #946 and #602.
@luto - Thanks for the hint, I completely forgot, that I have to update my fork on github. Sorry.
> [flask] Update guide, fix #946

- source/guide_openslides.rst
Important information for OpenSlides instances on Uberspaces that would like to upgrade to v3.4 or higher.
see: https://github.com/OpenSlides/OpenSlides/discussions/6283
> [OpenSlides] Add a info in upgrade section

- source/guide_rocketchat.rst
https://docs.mongodb.com/manual/tutorial/enforce-keyfile-access-control-in-existing-replica-set/
Close #1145
> fix guide_rocketchat.rst

- source/guide_bitwarden.rst
Updated bitwarden_rs naming to vaultwarden and updated the git pull command to reflect the checkout of the async branch earlier.
> [vaultwarden] Updated naming and commands

- source/guide_bitwarden.rst
Resolves #1164, resolves  #1160, and resolves #708
> [vaultwarden] Rewrite, Using pre-built binaries

- source/guide_conduit.rst
Thanks to @23n for reporting this in https://github.com/Uberspace/lab/pull/1065#issuecomment-1002468688
> [Conduit] Fix database path in config file

- source/guide_starship.rst
This is a follow-up for #1183 to incorporate @pascoda's [suggested changes](https://github.com/Uberspace/lab/pull/1183#issuecomment-1030004754). Kudos for that!
Just started a new job, so didn't have the time to give this an in-depth review again before committing. But also didn't want to leave this sitting any longer. Let me know if anything else needs changing after your review. Thanks! :-)
> [Starship] Add @pascoda's suggested changes

- source/guide_synapse.rst
Updating python3.6 to 3.9: matrix-synapse >1.51 not supported anymore.
https://github.com/matrix-org/synapse/pull/11683
> [synapse] update python version

- source/guide_umami.rst
Fixing build SWC build error: https://nextjs.org/docs/messages/failed-loading-swc
> [umami] fix build error

- source/guide_ghost.rst
> [ghost] switch to ghost-cli's `ghost update`

- source/guide_typo3-cms.rst
> [typo3] update TYPO3 CMS guide for version 11.5 LTS

- source/guide_lychee.rst
This PR sets the used PHP version to 8.1  and implements
the new installation instructions of the source - https://github.com/LycheeOrg/Lychee
> [lychee] Fix/Update guide

- source/guide_writefreely.rst
> [writefreely] corrected typos and author information

- source/guide_django.rst
because of https://github.com/Uberspace/lab/issues/1297
> [Django] replace uwsgi with gunicorn

- source/guide_simpleid.rst
> [simpleid] works with PHP 8.0

- source/guide_freshrss.rst
> Freshrss php8

- source/guide_limesurvey.rst
> Limesurvey php8

- source/guide_kimai.rst
Update to kimai2 1.28.1 and PHP 8.1
close  #1386
> Kimdiallo [kimai2] check for php 8.0 compatibility

- source/guide_mattermost.rst
see also https://docs.mattermost.com/install/self-managed-changelog.html#id84
> [mattermost] add update instructions for v6.4 and newer

- source/guide_synapse.rst
> added Tag "matrix" to guide_synapse.rst

- source/guide_statping.rst
> Replace statping with statping-ng

- source/guide_code-server.rst
Seems to have changed in current versions
> [code-server] Fixed path to code-server binary

- source/guide_libreoffice.rst
The container.json in collabora/code has changed
> [libreoffice] change JSON config container user extraction

- source/guide_code-server.rst
Updated tar names according to current release and added /bin/ to path of the binary as it was introduced.
> Code server update path structure

- source/guide_bludit.rst
removed lots of information that can also be found in the Bludit documentation; added a general link to the docs.
> [bludit] update for PHP 8.1, clean

- source/guide_contao.rst
Also use the `contao-manager.phar` for the instalation / update.
> [contao] update to version `5`

- source/guide_mumble.rst
update guide, for details see: https://github.com/Uberspace/lab/issues/1191#issuecomment-1340080197
closes #1191
> [mumble] fix broken guide

- source/guide_radicale.rst
... also, put "Start Service" before "Configure web server" such that the output there, reporting a "listening: PID...", is actually correct.
> [radicale] start service before web server config

- source/guide_django.rst
when ready, closes https://github.com/Uberspace/lab/issues/1486
> [django] update guide

- source/guide_uu-notify.rst
> [uu-notify] update guide

- source/guide_mongodb.rst
Added instructions to access MongoDB externally without an SSH tunnel
> [MongoDB] Extended the guide

- source/guide_shopware-6.rst
- Fix download URL
- Update PHP configuration for Shopware
- Add note to reload PHP after configuration changes
> Update Shopware 6 guide

- source/guide_mattermost.rst
> [Mattermost] fix update script to follow API call redirect

- source/guide_nextcloud.rst
fixes https://github.com/Uberspace/lab/issues/1562
> [Nextcloud] Use USER var in commands

- source/guide_mattermost.rst
* Make setup easier to read
* Add comment on user creation
> Improve mattermost

- source/guide_mailman-3.rst
* `enviroment` was misspelled and unused
* `startsecs` moved to supervisord config file
> [mailman3] fixed minor issues

- source/guide_baikal.rst
Added one sentence with link to above script which i wrote for periodic checks on baikal updates.
> [baikal] mentioned baikal_updates script

- source/guide_mosquitto.rst
Support added this line to my config, so i guess it might be a good default!
> Update guide_mosquitto.rst startsecs for daemon

- source/guide_mailman-3.rst
> [mailman3] fix dependencies

- source/guide_grafana.rst
Added two lines and tested it on the latest uberspace release
> Update to work for Grafana 10.0.5

- source/guide_castopod.rst
The cron call has changed. I also noticed I had to set the `RewriteBase /` with a installation on a custom subdomain (YMMV?), otherwise I would get a Error 500.
> Update guide_castopod.rst for v1.5.2

- source/guide_the-lounge.rst
> check for new nodejs version compatibility #1605

- source/guide_up1.rst
> check for new nodejs version compatibility #1607

- source/guide_uptime-kuma.rst
> check for new nodejs version compatibility #1608

- source/guide_jingo.rst
Works still fine with Node 20 :)
closes #1602
> [jingo] Update guide for Node 20

- source/guide_hasteserver.rst
Hey,
everything seems to be working fine with node 20. Tested file storage, redis and postgresql. No issues so far.
I also updated the repo URL, changed the configuration snippets to be more clear and added `stopasgroup=true` to the supervisord configuration. Without this option the service would not stop correctly.
Closes #1600
Best,
Malte
> [hasteserver] Update guide to node 20

- source/guide_cryptpad.rst
Hi,
still works like a charm.
I added a paragraph about node 20 and removed everything related to `Bower` since it isn't used anymore.
Closes #1595
Best,
Malte
> [cryptpad] Update guide to node 20

- source/guide_cloudlog.rst
Hi,
everything still works as expected.
Closes #1653
Best,
Malte
> [cloudlog] Update guide to PHP 8.2

- source/guide_hugo.rst
I updated the guide with configuration directives that replace an environment variable and a runtime argument, making Hugo much more user friendly to use.
I also updated the version numbers.
> [hugo] configuration improvements, version bump

- source/guide_flatboard.rst
Still works as expected.
Closes #1655
> [flatboard] Update guide to PHP 8.2

- source/guide_linkace.rst
Works as expected.
Closes #1657
> [linkace] Update guide to PHP 8.2

- source/guide_code-server.rst
See #1680 for any further information. 
Closes #1594
> [code-server] Mark guide as broken

- source/guide_mautic.rst
https://github.com/Uberspace/lab/issues/1692
> [mautic] add broken message

- source/guide_symfony.rst
Everything is checked and still works with PHP 8.2
Resolves #1665
> Update Symfony Guide for PHP 8.2

- source/guide_synapse.rst
That escalted quickly. Did some minor changes as preparation for Matrix 2.0.
* Link to the Uberspace 6 guide is offline
* Updated the use of domains for a better preperation on uberspace with additional services like sliding sync or audio / video calls
* Add a hint for urllib3. On a new uberspace urllib3 v2 will be automatically be installed and does not support OpenSSL 1.0.2 anymore
* Removed some obsolete steps (e.g. public_baseurl uses as default the server-name) 
* Added configuration of sliding-sync
I hope I didn't overengineered it ;) 
closes #1625
> [synapse] Update guide / Add sliding sync

- source/guide_mongodb.rst
(Trying to set up mongodb right now and thought I was going bananas...)
> typo: replaced isabell with <username>

- source/guide_dendrite.rst
From the [Dendrite website](https://matrix-org.github.io/dendrite/):
Dendrite is a second-generation Matrix homeserver written in Go! Following the microservice architecture model, Dendrite is designed to be efficient, reliable and scalable. Despite being beta, many Matrix features are already supported.
It is an alternative to Synapse and Conduit and—based on my experience—works well on Uberspace. I have it running for several month now. Here is how I set it up.
Please let me know of any feedback.
> Add guide for Dendrite (close #1712)

- source/howto_automatic-deployment.rst
"Small change to emphasize actions primarily on the user's local machine."
> Automatic deployment

- source/guide_onionservice.rst
Hello everyone, 
I wrote a little guide how to install tor and setup an onion service in your uberspace.
I hope it might be helpful. :)
I'm very new to the used .rst format, so probably I made some errors in the style/formatting. I'm looking forward to any feedback! :)
> Add guide for tor onion service

- source/guide_ntfy.rst
This PR references #1728.
I have run the pre-commit hooks and the linter, but it gave me errors for guides i did not work on, so I did not commit them, I hope that's okay.
> [ntfy] small config updates

- source/guide_privatebin.rst
Just adding a link to privatebin :)
> fix: adding link to privatebin website

- source/guide_synapse.rst
> fix manual execution of syncv3 - username was executed

- source/guide_bookstack.rst
Greetings,
- added an example mail config --> resolves Uberspace/lab#834
- new account on Uberspace 7.15.15, fresh installation of BookStack 24.05.2, working just fine after following the guide, tested shelves, books and pages (creating and deleting), email notifications also working, no error 500 during testing --> closes Uberspace/lab#1499
> [bookstack] Update Guide

- source/guide_pretix.rst
The official documentation https://docs.pretix.eu/en/latest/admin/installation/manual_smallscale.html#updates lists an additional steps for updates (prefix updateassets). And for the update to 2024.7.0 it seemed to be necessary. So I added it to the update guideline.
> Update process changed guide_pretix.rst

- source/guide_forgejo.rst
I've tested this with Forgejo 7.0.3 and updated the guide. It's no longer necessary to link the .ssh directory, see #1735.
Moreover, I've moved the section about SSH key setup from the _optional_ configuration to the _needed_ configuration, because I think there is a real risk to lock oneself out of Uberspace. This can be fixed, of course, but I think that this is a major pain point for newcomers.
> Update guide_forgejo.rst. Fixes #1735

- source/guide_moodle.rst
Fixes #1779 and fixes #1659, replaces #1780.
> [moodle] Update guide to use Moodle 4.4.1 and PHP 8.3

- source/guide_hedgedoc.rst
HedgeDoc reached version `1.10.0`, so the simple string comparison does not work anymore as the string value of 1.9 is higher than 1.10 so the update script needs a better method. 
deploy preview: https://deploy-preview-1798--uberlab.netlify.app/guide_hedgedoc/#update-script
> [HedgeDoc] fix version check in update script

- source/guide_eturnal.rst
> [eturnal] fix spelling

- source/guide_snappymail.rst
@SalocinHB Since you have changed the code a bit we should also change the wording.
> [SnappyMail] adapt the wording to the changed code

- source/guide_wordpress.rst
closes #794 and adds instructions for performance optimization.
> Wordpress Performance & Optimization

- source/guide_phpbb.rst
> Update guide_phpbb.rst to 3.3.14

- source/guide_mediawiki.rst
tar expects filename before the option
> --strip-components after the filename

- source/guide_postgresql.rst
Adapt version list to current output on Uberspace.
> Update version list in PostgreSQL guide

- source/guide_keycloak.rst
> Update Keycloak guide

- source/guide_firefly-iii.rst
Updated Link to official setup guide and Tested with versions as reported in Issue #1731
> [firefly-iii] some minor updates

- source/guide_gotosocial.rst
> Update guide_gotosocial.rst: Typo

- source/guide_radicale.rst
> Update link to radicale documentation fixes #1894
