Uberspace/lab

source/guide_wallabag.rst
Because RST has problems with nesting links, this makes it possible to have an italic link
=> wallabag - fix link within italicized text

.gitignore, .gitlab-ci.yml, README.md, authorship/authorship/__init__.py, authorship/setup.py, requirements.txt, source/_static/css/custom.css, source/conf.py, source/contributors.rst, source/guide_etherpad.rst, source/guide_ghost.rst, source/guide_gitea.rst, source/guide_jingo.rst, source/guide_lychee.rst, source/guide_minim.rst, source/guide_wallabag.rst, source/guide_wordpress.rst, source/hall_of_fame.rst, source/index.rst
fixes #67 
- upgrade to py3
- upgrade sphinx to a dev version because of https://github.com/sphinx-doc/sphinx/commit/5ff7bc6dc6496080c569b56b8551f0d5b92986d3
- add authors to bottom of each guide
- add "hall of fame" listing all authors
TODO:
=> Display the authors of our lovely guides

source/_static/js/custom.js
I can't reproduce https://github.com/Uberspace/lab/issues/89 locally, but it seems, that the function call fails (since `UberLab launched…` is always printed to the console). So… I wrapped the check in a ready function :crossed_fingers:
=> wrap logo–check in jQuery ready function

source/_static/css/custom.css
Use little rocket icons as bullets in front of the guides in the _Hall of Fame_.
=> :bento: use rocket icon for guides bullet

source/guide_nextcloud.rst
The current guide for Nextcloud uses a wrong path for the cron script under `$HOME` instead of the installation directory `/var/www/virtual/$USER/html/`. Commit 654abaa fixes this.
Additionally commit dd70a51 logs the output of the cron script to `$HOME/logs/nextcloud-cron.log` which might be useful for maintenance and debugging.
=> Fix Nextcloud cron script path and log script output

source/guide_kirby.rst
Thanks for merging the Kirby guide! 
I noticed the rst markup for the author display at the end of the guide is missing. This feature was introduced when the guide was already in review/updated and I missed that.
=> Add missing rst markup to display author at the end of the Kirby guide

source/guide_kirby.rst
Sorry, I also missed that you renamed the sectionauthor variable to author. Hadn't tested it because of my outdated local build environment. Sorry about that, updated everything. 🙈
=> Rename sectionauthor variable to author in Kirby guide

source/guide_wordpress.rst
I don't know if this is worth updating for minor point releases but for what it's worth, we just tested it with 4.9.6.
=> We just tested it wordpress 4.9.6

README.md
I find it usefull to have a link to the already built online version in the Readme.
=> Link official version in Readme

source/_templates/breadcrumbs.html
Closes #146.
This adds a Link to the Changelog next to the "Edit on GitHub" link.
=> Add guide specific changelog to each guide.

source/guide_gitea.rst
Fix a typo in the Gitea documentation.
=> Fix Typo 'diretory' -> 'directory'

source/guide_eqdkp-plus.rst, source/guide_kirby.rst, source/guide_resilio.rst, source/guide_ttrss.rst, source/index.rst
There are some syntactic errors in the docs that lead to 11 warnings.
One error even leads to a missing headline.
This commit fixes all the warnings.
=> Fix build warnings

source/guide_gitea.rst
`supervisorctl stop gitea` is needed to be able to overwrite the executable.
=> Gitea: Bump Version and add SSH key management through gitea

.editorconfig
According to EditorConfig specifications (see https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties)
the value yes is not supported and must be true instead.
Resolves: #174
=> [BUGFIX] Correct settings in .editorconfig

source/guide_lychee.rst
the lychee repository moved from private to an organisation (see https://github.com/electerious/Lychee/issues/763#issuecomment-398303752)
=> lychee - fixed github repo (moved to organisation)

source/_static/css/custom.css
The atom image on the front page is rendered in front of the text because the file specified as shape-outside does not exist. Adding `/en/` as url prefix resolves this issue.
Before:
After:
=> Fix wrong shape-outside for atom image

.gitignore
The built-in `venv `module of python3 creates a folder called Scripts, this is currently not ignored.
This PR adds the directory to the environment ignores.
=> Add windows venv folder gitignore

source/guide_kirby.rst
I improved the Kirby guide with a better placement of the license information utilizing the new "License" section. Also added a link to the official EULA. Should avoid confusion putting this at the beginning of the guide.
=> Kirby Guide: Improve information on licensing

source/guide_etherpad.rst
for example the current 1.7.0 is not heaving an branch called release/1.7.0
but there is a tag for it.
=> [etherpad] use tag instead of branch

source/guide_etherpad.rst
Since "66.6.6" is used as pseudo version number in the rest of this tutorial, it should be used in the update section as well. This will prevent irritations.
=> Correct pseudo version number

source/guide_buildbot.rst
%(ENV_HOME)s were wrongly entered from memory, restart command has changed (since managed by supervisord now)
=> Fix typo in service commands

make.bat
This adds a make.bat to be able to build the Sphinx HTML on Windows. The original file comes from Sphinx directly (see [here](http://howto.nspx.ca/how-to-sphinx.html#using-sphinx-autobuild)) and has been adjusted for Uberlab. 
In a virtual environment, run ``make.bat html`` just like you would do on Linux:
```
(venv) PS R:\uberlab> .\make.bat html
[...]
The HTML pages are in build\html.
(venv) PS R:\uberlab> 
```
=> Add make.bat for windows machines

source/conf.py, source/guide_akaunting.rst
This enables the official [`extlinks`](http://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html) to improve links to the manual (see #262).
With this change referencing the manual is possible using one of the following directives:
```rst
* :manual:`Python <lang-python>`
* :manual_anchor:`Change Python version <lang-python.html#change-version>`
```
There are two different directives at the moment to support anchors while avoiding having to write the `.html` part in the "default" case. This may be changed if needed - as well as the naming of the second directive.
An additional change is to unify the indentation of the code inside the configuration file according to the values inside the `.editorconfig` file.
=> Enable `extlinks` extension

requirements.txt, source/conf.py, source/guide_babybuddy.rst, source/guide_bludit.rst, source/guide_miniflux.rst
This changes the `:lab:` and `:lab_anchor:` directives to create domain-less links instead of the old ones enforcing links to `lab.uberspace.de` as discussed in #331. Additionally a broken link in the Miniflux guide gets fixed and the new guides are ported to use the directives if needed.
Besides this I updated the `requirements.txt` file to use a newer `sphinx-rtd-theme` version and to get rid of the Git commit for `sphinx` as the corresponding version mentioned inside the comment has been published nearly a year ago.
=> Do not use hardcoded lab URL for directive

source/guide_simpleid.rst
Using a time stamp to derive randomness is critical as it allows informed
attackers to bruteforce the random information. While the implications in the
Uberspace setting might be manageable, it is still bad habit and should be
avoided at least for the sake of example.
This commit derives the salt from /dev/urandom, which is a cryptographically
sound source of randomness available on all Linux systems.
=> [simpleid] Use real random source to generate salt

source/guide_mailman-3.rst
Removes the warning about web backends and possible workaround as the guide has been updated.
Was originally done in #359 but unforunately forgotten in necessary manual merge.
=> [mailman3] Remove web backend warning

source/guide_mailman-3.rst
Fixes #362 (update strategy), fixes #344 (.qmail handling and proxy headers), adds a "not working" note for #363 (archiving does not work).
While update strategy, proxy headers and archiving are quite clear, the changes to the .qmail handling might need discussion. 
When leveraging ``.qmail-default`` for forwarding all incoming mails to mailman, some emails that have been received before might be getting lost. Therefore I added a warning as well as a note about manually adding .qmail-listname files (i.e. the old way, without an additional script).
=> [mailman3] Polish guide & fix issues

source/guide_nextcloud.rst
I added information to the nextcloud entry on how to increase the php memory limit to the recommended value of 512 MB.
=> Information on how to increase php memory limit

source/_static/images/go.svg, source/guide_go.rst
This is a new version of #382 which doesn't use linuxbrew.
This closes #379 
.Merging this should alse help #353 to continue as Buffalo seems to need a running go installation.
=> [go] add guide for go

source/guide_django.rst
I suggest a paragraph on how to configure MySQL, since the uberspace version of sqlite is not supported by django 2.2 anymore.
=>  configure MySQL instead of sqlite

requirements.txt, source/404.rst, source/conf.py
I added a **404** - page using [sphinx-notfound-page](https://sphinx-notfound-page.readthedocs.io/en/latest/).
The 404.rst file is not rendered in the TOC but will be converted to a 404.html file that is displayed on netlify, if a broken link is clicked :)
Maybe someone knows a neat little gif, that fits onto that page :laughing: 
Issue: #269
**Screenshot**:
=> Add 404 page (not found)

source/guide_django.rst
Assuming a pretty standard Django project setup, with a /static folder inside the application and /static URLs to access the resources.
See https://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html
=> [django] Add support for static files

source/guide_ghost.rst
Changing the internal uber.space URL to an external URL with ghost command line as stated in the Ghost manual does not completely work as the users do not have root privileges to run sudo, the config files have to manually be updated as there is a change in the host IP address and the process has to be restarted with ``supervisorctl`` instead of the ghost-cli. Therefore I added this section to clarify such a change of the URLs.
=> Added External URL Support section

source/includes/open-port.rst
=> Harmonize indentation of code blocks in includes

source/guide_mongodb.rst
although both are stored in the admin database, [root](https://docs.mongodb.com/manual/reference/built-in-roles/#root) and [admin](https://docs.mongodb.com/manual/reference/built-in-roles/#dbAdminAnyDatabase) users are 2 different things.
=> corrected wording to avoid misunderstandings

source/guide_simpleid.rst
Unfortunately, the example is wrong and if you follow it is not possible to login to the simpleid dashboard
=> adds the missing 100000

source/guide_codimd.rst
[Version 1.5.0](https://github.com/codimd/server/releases/tag/1.5.0) of CodiMD was just released.
I verified that the current guide still works for the new version and improved three minor aspects.
=> Update CodiMD guide for latest 1.5.0 release

source/guide_contao.rst
On a fresh Uberspace U7 account, I could not allocate enough memory to run the `composer` call locally. The obvious `php -d memory_limit=-1` does not do the trick, as well as a custom php.ini config. Therefore I experimented with the Contao Manager beta product and contribute the successful outcome.
=> Add Contao Manager as alternative install method

source/guide_django.rst
curl -I localhost:8000 is misleading cause localhost is not part of the ALLOWED_HOSTS and so it spawns 400.
=> remove `curl -I localhost:8000` from guide_django.rst

source/guide_neos.rst
Closes #484
Changed: 
* mention PHP 7.2 as base requirement and tell users to set this version manually
* update outdated link to upgrade instructions
* bump "tested with"
=> Update Neos guide for version 5

source/guide_akaunting.rst, source/guide_bookstack.rst, source/guide_grav.rst, source/guide_kirby.rst, source/guide_neos.rst, source/guide_octobercms.rst
I'd like to change the author attribution in my guides from a mail adress to my URL (in order to avoid emails regarding the guides). Thanks!
=> Change author attribution in my guides

source/guide_resilio.rst
Opening a custom port allows Resilio Sync to establish direct connections to peers,
instead of relying on a relay server.
Setting the "listening_port" has to be done through a configuration
file. For consistency, all command line arguments  are included in this file.
=> [resilio-sync] Add step to open a firewall port for Resilio Sync

source/guide_mosh.rst
In case local and remote usernames differ the remote username has to be specified in the mosh address.
=> Add <username> as remote user

source/guide_synapse.rst
It's the only supported configuration in recent Synapse versions.
https://github.com/matrix-org/synapse/blob/master/docs/postgres.md#set-up-database
=> use lc-collate and lc-ctype C during createdb

source/guide_matomo.rst
While the old method still works the recommended official way looks a [little different now](https://matomo.org/docs/installation/).
I've also deleted some of the output `wget` creates, since it isn't helpful for the installation and clutters the manual.
=> Docs: update Matomo installation manual

source/guide_kimai.rst
I just installed Kimai on my U7 and updated the lab guide regarding version and secret during the installation. 1.8 also works fine on U7.
=> Kimai: Bump versions, add update of app_secret

source/guide_postgresql.rst
To avoid confusion in the install process I reordered the install steps just as we discussed in our email correspondence.
=> Postgres guide: order install steps to be more intuitive

source/guide_etherpad.rst
https://lab.uberspace.de/guide_etherpad.html says in a box:
> etherpad-lite is running on port 9001. Additionally, the --remove-prefix parameter is needed.
In the following example, the `--remove-prefix` parameter is, however, not used. As far as I understand, it is only needed if one wants to run Etherpad Lite under a sub URL like `/ep`.
=> Clarify --remove-prefix

source/guide_goaccess.rst
The default configuration seems to have been moved to `etc/goaccess/...`.
=> [goaccess] update location of the default configuration

source/guide_kanboard.rst, source/guide_mailman-3.rst, source/guide_matomo.rst, source/guide_passbolt.rst
Some crontab entries used isabell as username. This could be more generic to avoid errors of users by using $USER
=> Make crontab entrys generic using $USER

source/guide_cryptpad.rst
Since CryptPad version 2, the structure of `config.js` changed substantially, so I updated this guide for the current release 3.16.0.
=> [cryptpad] Updated for CryptPad 3.16.0

source/guide_ghost.rst, source/guide_matomo.rst
Sphinx throws currently four warnings during the build. This fixes the warnings
=> Remove build warnings

source/guide_etherpad.rst
I installed etherpad-lite on my space and update the guide accordingly to the current version.
=> [etherpad-lite] Update guide to 1.8.3

source/guide_nextcloud.rst
Sometimes an update leaves you stuck in maintenance mode.
I've added a line to the shell commands of the update section which disables maintenance mode. It should be safe to always call this, even if maintenance mode is already disabled.
=> Add shell command for disabling maintenance mode after update

source/guide_redis.rst
Seems like Redis >= 6.0.0 fail to build with the GCC version available on uberspace. Using clang works.
See https://github.com/antirez/redis/issues/6286
Note: This is up for discussion. I just tried to installing redis using this guide and it failed. Using clang worked. But maybe there is a better solution?
=> Use clang to build redis

source/guide_alertmanager.rst, source/guide_grafana.rst, source/guide_prometheus.rst
Hi,
I updated the versions of alertmanager, prometheus and grafana.
grafana: `6.3.5` -> `6.7.3`
prometheus: `2.12.0` -> `2.18.1`
alertmanager: `0.19.0` -> `0.20.0`
"tested w/ uberspace": `7.3.6.1` -> `7.6.1.2`
Best,
Malte
=> Update alertmanager, prometheus and grafana versions

source/guide_selfoss.rst
When I tried the selfoss guide, I ran into the issue that the `/update` endpoint cannot be curl'ed with the default config (error: "unallowed access"). There are two ways to remedy this situation:
1. set the `allow_public_update_access` to `1` (default is unset) and continue to GET the `/update` endpoint, or
2. use the php interpreter to directly call the `cliupdate.php` script
I went for option 2 as it keeps the selfoss instance fully password protected and no authorized endpoints can be called. I have been using this setup successfully for a couple of days. The use of the `cliupdate.php` script is documented in the [offical installation instrucitons](https://selfoss.aditu.de/#installation).
=> [selfoss] Update selfoss guide to use cliupdate.php for updates

source/guide_nextcloud.rst
HSTS header default has been changed by Uberspace and nextcloud will no
longer complain
=> [nextcloud] remove HSTS info

source/guide_synapse.rst
TLS certificates are not used in reverse-proxy setup, because nginx is already handling TLS. See also hint in the generated config file
```
listeners:
#
#
#- port: 8448
```
which states that TLS needs to be configured *if* this listener were enabled
=> [synapse] remove TLS certificate section

source/guide_icecast2.rst
To me icecast2 configuration is missing SSL option for secure connection to admin interface and streaming option via HTTPS. I'm wondering why this has not been considered although it's mentioned in official documentation at https://icecast.org/docs/icecast-2.4.1/config-file.html#path.
=> Add SSL configuration to guide for icecast2

source/guide_ejabberd.rst
The value for put_url has to contain "upload." in front of @HOST@ to apply to subdomain configuration in the beginning of this guide. Otherwise uploading media files won't work.
=> Fix put_url in configuration

source/guide_bludit.rst, source/guide_ezmlm.rst, source/guide_flatboard.rst, source/guide_ioncube.rst, source/guide_taskd.rst
Using $HOME instead of '/home/isabell/' makes snippets more friendly for copy-paste workflows.
The replacement was done only in snippets of Bash code.
=> Replace /home/isabell/ with $HOME

source/guide_wordpress.rst
The naming of a database is bound to the username.
=> Wordpress: Add note on database naming restriction.

source/guide_radicale.rst
Just tried to follow the guide to install `radicale>=3` and got the following error in `~/tmp/radicale-stderr---supervisor_[...].log`: 
```
usage: radicale [OPTIONS]
radicale: error: unrecognized arguments: -f
```
Also updated the links to changelog & documentation.
=> Update guide for Radicale 3.0

source/guide_gollum.rst
Gollum is a simple wiki software written in Ruby. It is the software component that drives many popular wiki integrations (e.g. GitHub and GitLab wikis). It is a very simple, small and fast wiki alternative to larger systems like Dokuwiki. Gollum is Git-backed, so all changes made through the web interface are also committed to the underlying Git repository.
=> [gollum] add guide for gollum

source/guide_jenkins.rst
Jenkins officially does not support Java 14 as they only allow Java 8 and 11.
This is not going to change in the near future, but they have a flag to allow running Jenkins with the newest Java version.
This change introduces this flag to the guide.
=> [Jenkins] Update guide to work with Java 14

source/guide_ejabberd.rst
The guide for “ejabberd” is a good starting point but I find it incomplete for a production instance. This PR adds configuration options for MySQL, the [compliance test](https://compliance.conversations.im/) and several security options and adds some maintenance notes. Additionally it improves the structure a little bit.
=> Extend ejabberd guide

source/guide_nextcloud.rst
Since the web-based updater is still prone to errors and slow, the command line tool should be used.
In order to save some time for the user I provide useful commands as a script.
=> [nextcloud] add script for command line based updater

source/guide_lychee.rst
Updated for version 4.x of Lychee by putting Lychee data outside the DocumentRoot and creating a Symlink to the "public" subfolder as required.
=> [Lychee] Update for version 4.x

source/guide_nextcloud.rst
closes #728 
Command "db:add-missing-columns" is not defined in NC < 19.
There will be displayed a dominant warning which may confuse some users.
So I think the command should be disabled by default until NC18 is `end of life`
=> [nextcloud] :bug: fix #728 for new db command in NC<19

source/guide_postgresql.rst
"Replace replace" makes no sense. Therefore changed to "Please replace" as it is also shown in other parts of the manual.
=> [PostgreSQL] Fixes a spelling mistake

CONTRIBUTING.md
> If you want to stay informed of changes to your guide or a guide in your interest you can subscribe to its commit feed.  
> e.g. for Nextcloud it would be: https://github.com/Uberspace/lab/commits/master/source/guide_nextcloud.rst.atom
I think some contributors would like to watch changes to a specific guide as they may not like the default flood of watch notifications by GitHub.
I'm not sure if this is the right place for this information. Maybe each guide could also have such an information like the "View Changelog" link.
=> [CONTRIBUTING.md] add note on commit feeds

source/guide_pleroma.rst
New dependencies in the pleroma version 2.1.0 needs minimum OTP22.
=> [pleroma] add instructions for erlang version

source/guide_mailman-3.rst
These commits update the guide to use python3.8, as proposed in #763, and include an example configuration for mailman hyperkitty. It fixes #765 by using the more recent python installation and makes #764 obsolete, by making the guide usable again.
=> [mailman3] updated python version, added hyperkitty installation hints

source/guide_restic.rst
Closes issue #759 
Tested Restic version 0.10.0 on Uberspace version 7.7.7.0 and have updated guide to reflect on new update.
A link to the Restic documentation on where to find the public GPG key of the maintainer that publishes new releases, have also been added.
=> [RESTIC] update to 0.10.0

source/guide_nextcloud.rst
While there is an official RSS feed, it's very noisy and doesn't only contain information about new releases. The Github releases feed serves this purposes (but it is very bare and also includes unstable releases). A more advanced solution might use the output of "occ update:check" to send an email to the user whenever there is a new release.
=> [nextcloud] Add reference to Nextcloud release feed on Github

source/guide_rocketchat.rst
Hi,
I've updated my Rocket.Chat guide because Rocket.Chat has released version [3.7.0](https://github.com/RocketChat/Rocket.Chat/releases/tag/3.7.0), which has my pull request https://github.com/RocketChat/Rocket.Chat/pull/17012 included, so we can now set `TMPDIR` and the workaround in my original guide is not longer necessary.
=> Rocket.Chat guide update

source/guide_akaunting.rst
https://akaunting.com/docs/requirements
Akaunting requires "PHP 7.2.5 or higher". Since 7.2 is the oldest available version, I think we can just drop the notice about the requirement. I could also update it to 7.4 and mention that anything 7.2 or above should work, if that'd be better.
=> [akaunting] Remove PHP version from Akaunting guide

source/guide_nextcloud.rst
I've added some troubleshooting info.
Here is an example you probably don’t want to keep on your Uberspace. To get rid of the old version navigate to that path and run: `rm --recursive nextcloud-19.*`
```
ncdu 1.15.1 ~ Use the arrow keys to navigate, press ? for help
--- /home/isabell/nextcloud-data/updater-ocRANDOMg5/backups ----
/..
1,8 GiB [##########] /nextcloud-20.0.0.9-1603717139
1,6 GiB [########  ] /nextcloud-19.0.3.1
1,6 GiB [########  ] /nextcloud-19.0.4.0-1601738662
Total disk usage:   4,9 GiB  Apparent size:   4,7 GiB  Items: 132481
```
some other changes:
add some headings
move the update subscription info to the update section
remove restorecon noise on the update script
=> [nextcloud] howto remove backups

source/guide_baikal.rst
When Baïkal is not installed directly into the `html` DocumentRoot, PHP will throw warnings in the form:
```
LogicException: Requested uri (/dav.php) is out of base uri (/<username>.uber.space/dav.php/) in /var/www/virtual/<username>/baikal/vendor/sabre/http/lib/Request.php:184
```
when a WebDAV client tries to connect.
This can be fixed by editing the configuration file and setting the base URL.
=> [baikal] add info when installing to subdirectory

source/guide_prosody.rst
The guide for prosody was missing the one space identation in one code block, created warnings during build and weren't rendered correctly.
=> Remove build warning for prosody

source/includes/open-port.rst
Upon writing a guide we noticed syntax highlighting in the "open-port" include differs from other code blocks. It uses code-block [bash](https://pygments.org/docs/lexers/#pygments.lexers.shell.BashLexer), which is intended for bash scripts, but not for bash sessions. This PR changes it to [console](https://pygments.org/docs/lexers/#pygments.lexers.shell.BashSessionLexer).
=> [open-port] Fix syntax highlighting

source/guide_restic.rst
Update guide to restic version 0.11.0. 
`EXCLUDED_FILES` variable and `--exclude-if-present` flag have been moved out of the bash template, as it would create an error if list was empty.
closes #829
=> [restic] update to version 11 and edit minor details

source/_static/images/shiori.svg, source/guide_shiori.rst
Hello all,
I need help with this guide before #837 can be closed.
I've written guide_shiori.rst (my first guide) based on guide_gotify.rst. I have successfully tested
It's working with [https://shiori.uber.space](https://shiori.uber.space) and `uberspace web backend set / --http --port 8080` right now. ~~I've tried `uberspace web backend set /shiori/ --http --port 8080` with and without `--remove-prefix` before, both fail with error 404. Help would be appreciated.~~
=> [Shiori] Add Shiori install guide

source/guide_nextcloud.rst
The update script will not work unless it is executable.
=> [nextcloud] make update script executable

source/guide_nextcloud.rst
For installations it is strongly recommended to use the mysql backend because the sqlite one isn't performing very well.
=> Add a warning to use the mysql backend for nextcloud

source/guide_etesync-server.rst
Etesync Server version [0.5.0](https://github.com/etesync/server/releases/tag/v0.5.0) seems to introduce some major changes. It looks like this guide no longer works for the latest releases. So I removed all the parts that promote using a version after 0.3.0 until the guide gets updated.
=> [etesync-server] add warning about v2 incompatibility

source/guide_ethercalc.rst, source/guide_wekan.rst
Some tag variants have been renamed in favor of the [popular software link for nodejs in the manual](https://manual.uberspace.de/lang-nodejs/#popular-software).
=> fix nodejs tags

source/guide_wsgidav.rst
Explicitly set host ip address to 0.0.0.0
For Wsgidav to be usable as a web backend it needs to listen on 0.0.0.0:8080 and not localhost:8080, which is default.
Tested with wsgidav 3.1.0, Uberspace 7.8.1.0
=> [wsgidav] Fixed host ip address

source/guide_ghost.rst
We should update the mentioned Node.js version from v10 to v12, because v12 is the new Uberspace default (see https://manual.uberspace.de/lang-nodejs/) and it is also the recommended version of Ghost.org (see https://ghost.org/docs/faq/node-versions/).
=> [ghost] Updated section 'Prerequisites'

source/guide_ejabberd.rst
Align the installation path in the ejabberd guide with the description. Fix the compilation to run “make” before “make install” which is required for existing installations.
=> Fix ejabberd installation path and compilation command

source/guide_wordpress.rst
Using $USER in two places decreases the number of location the user of
the manual has to adapt to his needs.
=> [wordpress] Replace explicit mention of isabell by $USER

source/guide_nextcloud.rst
This PR is almost a complete rework of the guide using the Nextcloud command-line interface.
You actually don't need to touch the `config.php` file.
- enable redis caching #551
- enable URL rewriting (no more index.php)
- CLI based installation
- CLI based configuration
deploy preview: [guide_nextcloud.html](https://deploy-preview-887--uberlab.netlify.app/guide_nextcloud.html)
=> [nextcloud] add CLI install, CLI configuration, enable redis caching and URL rewriting

source/guide_mongodb.rst
MongoDB version 12 does not exist.
Adapted ``uberspace tools version use mongodb`` accordingly with the entry in the manual.
=> [mongodb] fix typo in version

source/guide_restic.rst
Update to restic [version 0.12.0](https://github.com/restic/restic/releases/tag/v0.12.0).
=> [restic] update to restic 0.12.0

source/guide_synapse.rst
Add note to update pip and install setuptools_rust in order to fix cryptography install error.
=> Add python crypto installation error solution note

source/guide_nextcloud.rst
Remove the App "document server community edition" (some kind of OnlyOffice), because of major flaws, see "Edits and changes made in Onlyoffice are not synced into Nextcloud #100" https://github.com/nextcloud/documentserver_community/issues/100
=> Remove the App "document server community edition" (some kind of OnlyOffice) due to major flaws (data loss!)

source/guide_mattermost.rst
Changing the relevant paths in the configuration to absolute ones is unnecessary.
I think it's easier to just start the service in the right directory.
=> [mattermost] add directory to service file

source/guide_nextcloud.rst
* use php 8.0
* fix new common admin warning for the missing default phone region
---
deploy preview: [guide_nextcloud.html#default-phone-region](https://deploy-preview-939--uberlab.netlify.app/guide_nextcloud.html#default-phone-region)
=> [nextcloud] update the guide according to Nextcloud 21 requirements

source/guide_bitwarden.rst
Changing the command for sqlite3 backup command since the tilde "~" in the backup file path generates the error on uberspace. Using ``$HOME`` instead. Also providing an alternative version of making backups with timestamp as file name (i.e. no file overwritten in cronjobs) if this meets user's need better.
=> Correct backup command, adding timestamp to backups

source/guide_nextcloud.rst
simple remove command for `nocontent.html`, otherwise updates wont work, could be made more sophisticated in the future
fix #996
=> [nextcloud] remove nocontent.html

source/guide_fastapi.rst
An [issue in a dependency](https://github.com/MagicStack/httptools/issues/59) previously limited usage to Python 3.8. Now that it's fixed, you can use the latest, Python 3.9.
I tested my way through the whole guide again to confirm it does work.
=> [fastapi] update guide after fix in dependency

source/guide_bitwarden.rst
bitwarden_rs was renamed Vaultwarden to avoid confusion with the official server implementation. Paths within the repository were also updated, so these instructions failed.
=> bitwarden_rs renamed to Vaultwarden

source/guide_statping.rst
Fixed missing URL for Statping in the intro session. Added https://statping.com/ as the main Statping URL since the Github link already points to the repository.
=> Fixed missing Statping URL

source/guide_mattermost.rst
The link to mattermost.com in the first paragraph of the description is missing
=> Update guide_mattermost: add missink link

source/guide_jekyll.rst
[isabell@stardust website]$ bundle install --path vendor/bundle
returns:
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
so I also adapted that part (to `config set`, followed by `install`), and (successfully) tested the adapted steps on another fresh uberspace.
=> [jekyll] udpate guide to current versions

source/guide_gitea.rst
According to https://docs.gitea.io/en-us/command-line/#admin it's `user create` instead of `create-user` now.
=> Create User CLI usage for Gitea changed

source/guide_prosody.rst
One should use domains like example.org or example.com in documentation, because they explicitly allow that kind of usage.
Other domains (like isabell.org) don't.
=> [Prosody] Use a suitable example domain

source/guide_prosody.rst
Siskin's development is more active that ChatSecure's.
Monal would also be an option.
=> [Prosody] Suggest a more modern client for iOS

source/guide_prosody.rst
What ciphers are modern changes over time, so it's good to leave that very internal and security-related configuration to package maintainers / developers / the OS.
If one wishes to only have very special ciphers, they'll find out how to do it. But "normal" users shouldn't configure something like this without knowing what they do.
=> [Prosody] Remove custom TLS configuration

source/guide_prosody.rst
Prosody developers discourage the use of MySQL.
Additionally, using file-based storage simplifies the installation process.
=> [Prosody] Use file-based storage

source/guide_umami.rst
* add a warning regarding the `next build` process ram usage, which will make it fail occasionally
=> feat: update umami guide how to limit nextjs ram

source/guide_synapse.rst
public_baseurl needs to be configured in order for the Synapse to be discoverable by clients.
Closes #1066
=> [Synapse] Add configuration of public_baseurl

source/index.rst
Since the list of guides is pretty long (yay!), maybe we could show the meta information before it in the navigation sidebar?
=> :lipstick: show meta before guides in navigation

source/guide_nextcloud.rst
As I ran to this issue today, I want to see it documented. I'm open for additional wording suggestions.
My setup migrated from U6 to U7. Formerly, I only had a php.ini with the content of Output Buffering and Memory Limit to be able to run Nextcloud.
The instructions here made many errors go away.
I only ran into some troubles with well known URLs but could resolve them. Do we want to document them here, too?
(Basically redirecting to index.php well-known URLs)
=> Notice the memory limit in PHP.ini

source/guide_conduit.rst
We changed stuff in the CI, which leads to a different download url.
=> [conduit] Update download url

source/guide_mailman-3.rst
Each worker process consumes 60MB memory. The default number of worker is equal to CPU count (ie. like 20, which uses way too much memory!!)
The other variables use the default values.
=> [Mailman 3] make Django Cluster use 4 worker processes

source/guide_uu-notify.rst
adding a section "Troubleshooting" to the guide, which links to the project's github issues having a label "workaround". Users might find quick notes about issues in newer releases and potential workarounds. This is a faster channel, than updating the guide for every new bug or resolved bug.
=> [uu-notify] add section "Troubleshooting"

source/guide_hedgedoc.rst
Changes:
- use Node.js 16
- increase readability of the update script
[👀 deploy preview](https://deploy-preview-1151--uberlab.netlify.app/guide_hedgedoc.html)
=> [HedgeDoc] 📝 use Node.js 16 as recommended

source/guide_nextcloud.rst
Changes:
- use PHP 8.0
[👀 deploy preview](https://deploy-preview-1152--uberlab.netlify.app/guide_nextcloud.html)
closes #1114
=> [Nextcloud] 📝 use PHP 8.0 as recommended

source/guide_synapse.rst
I got this warning:
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
=> use python3.6 -m pip instead of pip3.6

source/guide_focalboard.rst
Currently in the [Guide](https://lab.uberspace.de/guide_focalboard.html) this codeblock is not rendered, but instead printed as plain text.
=> [Focalboard] Layout: render code-block correctly

source/guide_nextcloud.rst
fixes #1187 
https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html#long-running-migration-steps
> From time to time we do some changes to the database layout that take a lot of time, but can be executed while Nextcloud **stays online**. Thus we moved them into a separate command that an administrator can execute on the CLI **without the need to lock the instance into maintenance mode** (at least for some of them).
=> [Nextcloud] remove maintenance mode from update script

source/guide_starship.rst
Signed up for Uberspace today, explored things a bit and realized that the documented way to install [Starship](https://starship.rs/) isn't working anymore. Taken this as an opportunity to contribute the below fixes:
The installation via cargo currently fails with the following errors:
```
Compiling starship v1.2.1
error[E0658]: use of unstable library feature 'command_access'
--> /home/fooforge/.cargo/registry/src/github.com-1ecc6299db9ec823/starship-1.2.1/src/utils.rs:392:56
|
392 |             log::info!("Unable to run {:?}, {:?}", cmd.get_program(), error);
|                                                        ^^^^^^^^^^^
|
= note: see issue #44434 <https://github.com/rust-lang/rust/issues/44434> for more information
error[E0658]: use of unstable library feature 'command_access' …
```
=> [Starship] Update install method, bugfixing, copy-editing

source/guide_directus.rst
This is an update to the Directus guide to include the change of the listening URL and create a web backend.
=> [directus] change listening URL, create web backend

source/guide_conduit.rst
The wget command places conduit in ~/bin/conduit, not ~/conduit
=> Fixed wrong directory

source/guide_kimai.rst
Uberspace 7.12 uses PHP 7.4 per default and Kimai has dropped PHP 7.2
since version 1.15.
Relevant kimai blog post:
https://www.kimai.org/blog/2021/php8-support-php72-dropped/
=> [kimai] remove obsolte PHP prerequisites instructions

source/guide_mailman-3.rst, source/guide_mailman.rst
The Uberspace SMTP servers accept max 100 recipients per mail. This PR updates the Lab guide for Mailman2 and Mailman3 to reflect these limits.
=> [mailman] configure max SMTP recipients limit

source/guide_gitea.rst
Changes:
- fix GPG key import
- add backup section
- add `gitea-update` script
tested by updating 1.14.4 to 1.16.3
[👀 deploy preview](https://deploy-preview-1215--uberlab.netlify.app/guide_gitea.html)
tested via
```bash
bash -c "$(wget -q -O - https://github.com/EV21/uberspace-helper/raw/main/uberspace-gitea-installer.sh)"
```
with
```bash
GITHUB_API_URL=https://api.github.com/repos/$ORG/$REPO/releases/tags/v1.14.4
GITHUB_API_URL=https://api.github.com/repos/$ORG/$REPO/releases/latest
```
=> [Gitea] rework guide

source/guide_libreoffice.rst
fixes #1178
fixes #1192
allows changing the wopi host setting after the first run
1. udocker installation changed upstream
2. `collabora/code` container changed upstream, e.g. admin console URL
3.  container `libreoffice/online` seems to be abandoned for the time being
4. `collabora/code` only allows to change the `domain` setting one time. Later changes take no effect. I found a workaround.
=> [libreoffice] update installation instructions for udocker and CODE

source/guide_searx.rst
At least one dependency of searx doesn't work with python version below 3.8 anymore, namely Flask, see here:
https://flask.palletsprojects.com/en/2.1.x/changes/
https://github.com/pallets/flask/pull/4335
=> Specify python version 3.8

source/guide_friendica.rst
Hi,
the latest stable release of friendica now supports PHP 8 and a vendored library requires it, so using PHP 7.4 in the guide has been the problem. I've fixed this now.
Regards,
Tobias
=> [friendica] fix guide - closes #1254

source/guide_postgresql.rst
It's `startsecs` not `startsec`.
=> Update guide_postgresql.rst: fix postgresql.ini

source/guide_couchdb.rst
It's a bit ambiguous whether this argument applies to `uberspace web ...` or the couchdb configuration.
=> Specify where `--remove-prefix` is needed.

source/guide_babybuddy.rst
Assuming that we'll use python 3.9 now.
Then we need to use uswgi with the same  version. Noted that in there.
mzsqlclient module is now always installed
=> babybuddy needs python3.7+ now

source/guide_gitea.rst
The HUP signal may result into forking the process into the backgroud, so it breaks the daemon when updating your instance.
Restarting or reloading are failing as the port is still in use by the forked instance.
https://github.com/alpinelinux/aports/commit/8a8c116a951f8c8a53be667e4697a76c97db93dc
Quick test:
```
bash -c "$(wget -q -O - https://sh.ev21.de/uberspace/gitea-installer.sh)" _ use 1.16.8
```
```
gitea-update
```
With this fix updates should run without any headaches.
[👀 deploy preview](https://deploy-preview-1314--uberlab.netlify.app/guide_gitea)
=> [Gitea] fix stop signal

source/guide_uptime-kuma.rst
Just tested updating uptime Kuma to the newest version 1.17.1, worked and added it as a comment at the end of the guide.
=> [Uptime-Kuma] Tested update for Uptime Kuma

source/guide_nextcloud.rst
add `sleep $(( 1 + $RANDOM \% 60 )) ;` to cronjob and explain why.
=> [nextcloud] add random sleep to cronjob in guide_nextcloud.rst close #1318

source/guide_contao.rst
When installing the latest version (`5.0`) dependencies require PHP `8.1`.
=> [contao] update PHP version to `8.1`

source/guide_nextcloud.rst
See https://github.com/nextcloud/server/issues/33048 for more background.
In a Nutshell:
* The contacts app makes many requests to load contact images like `/remote.php/dav/addressbooks/users/<user>/<Addressbook>/<contact-uid>.vcf?photo=`
* The `ProxyErrorOverride` config in Uberspace accounts hides the 404 error thrown by Nextcloud and opens the configured `ErrorDocument` from `.htaccess`
* The default error document redirects the user to the Nextcloud start page (Dashboard)
* This means a lot of requests are made at once to load the Nextcloud dashboard which can lead to a completely hung up Nextcloud instance until restarting the PHP service with `uberspace tools restart php`
=> [Nextcloud] Workaround for hanging contacts app

source/guide_nextcloud.rst
In my test run my credentials are
```sh
[test42@hadar html]$ my_print_defaults client
--default-character-set=utf8mb4
--user=test42
--password=-M,W:YO9123456.TZz1C
[test42@hadar html]$ NEXTCLOUD_ADMIN_USER='Testadminuser'
[test42@hadar html]$ NEXTCLOUD_ADMIN_PASS='superUnSafePässwörd'
[test42@hadar html]$ MYSQL_PASSWORD='-M,W:YO9123456.TZz1C'
```
The `--database-pass[=DATABASE-PASS]` has an optional argument (not like the other ones) and in my case the password starts with `-M,` so the Symfony CLI logic sees this thing as flag
with `=` it works
Since the official documentation also uses the space separation it looks like a bug.
https://docs.nextcloud.com/server/latest/admin_manual/installation/command_line_installation.html
Maybe just let us use the bulletproof connected variant to avoid …
=> [Nextcloud] make install command parameters bulletproof

source/guide_vaultwarden.rst
This PR moves both vaultwarden's `/data` directory as well as the `.env` file out of the `/output` dictionary, which gets overwritten with every update.
Therefore, one only has to stop vaultwarden, extract the latest update and is able to start it again.
=> [vaultwarden] Improve updateability

source/guide_cryptpad.rst
I tried to install Cryptopad as documented and failed. I actually believe the documented installation cannot work. The originally documented way makes the instance think it runs on localhost:3000 - the `httpUnsafeOrigin` which makes it fail. The way described here works.
=> Fix Cryptopad documentation

source/guide_restic.rst
When following the guide as it is, the cron logs showed the following error:
```
/home/<user>/restic_backup.sh: line 20: restic: command not found
```
This change made the script work in cron for me.
I don't know cron well enough to determine the proper way, so please correct me if there's a better solution.
=> [restic] use full path in backup script

source/guide_mongodb.rst
mongo is not shipped with mongodb version 6 but replaced with mongosh
=> Add note about mongodb v6

source/guide_mattermost.rst
I wrote myself an update script for mattermost and wanted to share it with everyone.
Open:
- Get the latest version of mattermost via a feed, so the version input is not needed.
Tried:
- Reading latest version from website (very cumbersome, but might be possible)
- Read latest version from Github (needs Auth)
- No directory listing via https://releases.mattermost.com/
=> [mattermost] Add automatic update script

source/guide_gotify.rst
We need to build from source since version gotify 2.1.7 as the released version requires GLIBC 2.28. Hopefully gotify won't use a glibc ABI only available in 2.28...
=> [gotify] Updated installation by building from source

source/guide_kimai.rst
This documentation seems to be a bit older, so I replaced the outdated stuff with up-to-date information.
- removed unneccessary steps
- replaced `kimai2` with `kimai`
- fix repo URL
See:
- https://www.kimai.org/documentation/updates.html
- https://www.kimai.org/documentation/installation.html
=> update kimai docs

source/guide_privatebin.rst
Enhance guide by instructions for read-only access for non-authenticated users using Basic Auth restriction for POST requests in .htaccess file.
I successfully implemented [a "read-only" restriction](https://github.com/PrivateBin/PrivateBin/wiki/FAQ#how-can-i-link-to-a-read-only-mode-where-users-cant-submit-pastes) on my instance of PrivateBin and would like to share my knowledge in the lab guide.
=> [privatebin] enhance guide

source/guide_forgejo.rst
The current compiled output is broken on https://lab.uberspace.de/guide_forgejo/, this small fix should solve the issue.
=> forgejo: convert markdown link to RST

source/guide_gitea.rst
- hide version number, so this info is only visable at `/admin` or via CLI
- I refactored a few things,
- removed some checks (they were actually added for debug reasons) as the issues should be fixed by the `fix_stop_signal` function,
- fixed a bug in the version comparator so it is not a tautology
- ignore versions with pre-release code words,
this is maybe important for Forgejo, but it looks like they now publish their pre-releases in another [repository](https://codeberg.org/forgejo-experimental/forgejo/releases),
so maybe a slightly changed version of this script (API requests) can be used for Forgejo,
- handle expired PGP keys
=> [Gitea] update the update script

source/guide_vaultwarden.rst
Since version 1.28.0, the ADMIN_TOKEN can be [hashed using Argon2](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token). This commit adds a section detailing how to use this feature.
=> [vaultwarden] Add section on securing the ADMIN_TOKEN

source/guide_nextcloud.rst
App updates may require additional steps to be done by the `occ upgrade` command.
Usually you would notice this by being redirected to an upgrade page in your browser.
So this should fix it:
=> [Nextcloud] add `occ upgrade` command for app updates

source/guide_hedgedoc.rst
> We recommend to use the latest LTS release of Node.js.
[tested versions](https://github.com/hedgedoc/hedgedoc/blob/1.9.8/.github/workflows/build-and-test.yml)
```yml
[...]
strategy:
matrix:
node: ['16', '18', '20']
[...]
```
<details>
<summary>clean manual install log 1.9.8</summary>
The app seems to work like expected via browser
```console
[test123@alpheca ~]$ uberspace tools version use node 20
Selected Node.js version 20
The new configuration is adapted immediately. Minor updates will be applied automatically.
[test123@alpheca ~]$ my_print_defaults client
--default-character-set=utf8mb4
--user=test123
--password=verysecrethaha
[test123@alpheca ~]$ VERSION=1.9.8
[test123@alpheca ~]$ wget https://github.com/hedgedoc/hedgedoc/releases/download/$VERSION/hedgedoc-$VERSION.tar.gz …
```
=> [HedgeDoc] use Node.js 20

source/guide_prometheus.rst
updated:
* prometheus latest LTS 2.45.0
* storage.tsdb.retention
changed web.listen-address to uberspace needs and [prometheus default](https://prometheus.io/docs/prometheus/latest/command-line/prometheus/) `0.0.0.0:9090`
=>  guide_prometheus: version bump, deprecated flag, listen-address

source/guide_gitea.rst
Use `PROTOCOL` instead of deprecated `MAILER_TYPE`
=> [gitea] update MAILER_TYPE to PROTOCOL (#1573)

source/guide_ejabberd.rst
I just checked my installation and found the missing module location. This is important during updates, because sometimes new files won't override the existing ones.
=> Update guide_ejabberd.rst: added module location

source/guide_ethercalc.rst
The guide works with current Nodejs versions.
Adapted version numbers in the guide to reflect this.
Closes #1598
=> updated ethercalc guide to current verified versions

source/guide_node-red.rst
The guide works with current Nodejs versions.
Adapted version numbers in the guide to reflect this.
Closes #1604
=> updated node-red guide to current verified versions

source/guide_magicmirror.rst
The guide works with current Nodejs versions.
Adapted version numbers in the guide to reflect this.
Closes #1603
=> updated magicmirror guide to current verified versions

source/guide_ackee.rst
With Node 17 ``127.0.0.1`` is required instead of ``localhost``, for whatever reason.
Also removed v2.0.0 hint because... its old and no one should using this version anymore :) 
closes #1593
=> [ackee] Update Guide for Node 18

source/guide_docusaurus.rst
So basically it works with Node 18 BUT this is a really outdated version.
In this guide Docusaurus 1.14.4 is described and there is already version 3.0.0 released.
I updated the guide for version 3.0.0 which works fine on my instance with the website template, I hope this is ok ;)
closes #1596
=> [docusaurus] Update guide for Node 18 and version 3.0.0

source/guide_mailman-3.rst
Mailman 3.3.9 is not compatible with Python3.8 anymore, I updated the docs while installing on 3.9
=> Update guide_mailman-3.rst to Python 3.9

source/guide_baikal.rst
A Baïkal setup may break when not backing up `baikal.yaml` due to database encryption not matching. The official [upgrading guide](https://sabre.io/baikal/upgrade/) recommends:
> Keep the whole Specific and config directories intact. Baïkal needs all files, not just the database.
=> [baikal] Add config/baikal.yaml to backup

source/guide_flarum.rst
Still works like a charm on PHP 8.2.
Closes #1654
=> [flarum] Update to PHP 8.2

source/guide_embetty.rst
Hi,
one thing that doesn't work reliably is downloading posters. It works on the first try but afterwards embetty-server throws 500s. I have no clue why or if it is related to node 20.
The main feature seems to work fine though.
Additionally, I
- removed the download-embetty.js section because the file is included in the server
- add a short example to show where the `embetty.js` file is located on the embetty-server
- added a license section
- mentioned the usage of node 20
Closes #1597
Best,
Malte
=> [embetty] Update guide to node 20

source/guide_couchdb.rst, source/guide_ejabberd.rst, source/guide_focalboard.rst, source/guide_gancio.rst, source/guide_influxdb2.rst, source/guide_jellyfin.rst, source/guide_keycloak.rst, source/guide_libreoffice.rst, source/guide_navidrome.rst, source/guide_offen.rst, source/guide_prosody.rst, source/guide_salt.rst, source/guide_shellinabox.rst, source/guide_tarsnap.rst, source/guide_teamcity.rst
I updated allmost all guides in the list where the tags where missing (some were already added).
I was unable to find the language of Resilio Sync, Teamspeak, as they are proprietary and only provide binaries.
The Web Key Directory (WKD) doesn't really have a language, as it's only a defined directory structure for PGP files.
I was unable to commit the guides for couchdb and gancio because they are missung the `Tested on Uberspace` part and I'm currently unable to do the tests myself.
The tags would be:
CouchDB
```
.. tag:: Erlang
```
gancio:
```
.. tag:: lang-php
.. tag:: lang-nodejs
```
#1612
=> [meta] added missing language tags

source/guide_flask.rst
The flask guide mentions "Configure nginx". Since the user doesn't interact with nginx directly (I'm not even sure if Uberspace uses nginx, IIRC it's Apache), this was confusing to me.
I propose a change to "Uberspace web backend", as this phrasing is used in the Gitea documentation (which I found super helpful).
=> Fix(NOISSUE): Remove mentioning "nginx" from flask guide

.pre-commit-config.yaml, source/guide_forgejo.rst
Guide is now up-to-date to match the current version of forgejo v1.21.3-0 released on Dec 22th 2023
=> ⬆️ Update forgejo guide

source/guide_postgresql.rst
The default postgresql.conf comments the line and this may be overlooked by users.
=> Changed warning in PostgreSQL config chapter

.pre-commit-config.yaml
```bash
$ pre-commit autoupdate
[https://github.com/pre-commit/pre-commit-hooks] updating v4.4.0 -> v4.5.0
[https://github.com/pre-commit/mirrors-prettier] updating v3.0.0-alpha.4 -> v4.0.0-alpha.8
[https://github.com/adrienverge/yamllint.git] updating v1.29.0 -> v1.33.0
[https://github.com/pycqa/flake8] updating 6.0.0 -> 6.1.0
[https://github.com/asottile/reorder_python_imports] updating v3.9.0 -> v3.12.0
[https://github.com/psf/black] updating 23.1.0 -> 23.12.1
```
```bash
$ git commit
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
trim trailing whitespace.................................................Passed …
```
=> Update linters in pre-commit configuration

source/guide_salt.rst
This change updates the brief description of SaltStack, with more metadata:
- Fixed the "missing" link to SaltStacks's project site
- Added link to source code on GitHub
- Added notes & link regarding their source code license
=> [salt] Update guide w/ links to source code & license

source/guide_hugo.rst
Tested with Hugo version: _hugo v0.123.3-a75a659f6fc0cb3a52b2b2ba666a81f79a459376 linux/amd64 BuildDate=2024-02-23T17:09:20Z VendorInfo=gohugoio_ another message is shown in the cli after successfully creating a new Hugo site. 
In order to keep the possible confusion for new users to a minimal, I have updated the output message.
=> Add new output for successful Hugo site creation

README.md, requirements.txt
Without the explicit declaration of this dependencies pip install incompatible versions for Sphinx 4.4.
Added the Enchant library as a prerequisite and that Python version must be less or equal to 3.11. As 3.12 doesn't support the `imp` library anymore ([0]), which is used by Sphinx 4.4.
Fixes #1739
[0]: https://docs.python.org/3.11/library/imp.html
=> Add specific dependency versions to `requirements.txt`

requirements.txt
Upgrade pre-commit from version 2.13.* to 3.5.* to avoid the following error:
An error has occurred: InvalidManifestError:
==> File /Users/<user>/.cache/pre-commit/repoyg3plrqf/.pre-commit-hooks.yaml ==> At Hook(id='black')
==> At key: stages
==> At index 0
=====> Expected one of commit, commit-msg, manual, merge-commit, post-checkout, post-commit, post-merge, prepare-commit-msg, push but got: 'pre-commit'
Fixes #1733
=> Use version 3.5.* of pre-commit to avoid InvalidManifestError

source/guide_foundryvtt.rst
Foundry VTT now requires minimum node version 16, 18 recommended
https://foundryvtt.com/article/requirements/#:~:text=Ability%20to%20run%20Node%2016%2B%2C%20(18%20recommended)
=> Bump Dep Ver for Foundry Guide

source/guide_resilio.rst
Resilio Sync recently pushed an update (so they are not dead, yay!).
Download URLs have changed, so these needed adjustments.
=> Update guide_resilio.rst to 2.8.1

source/guide_moodle.rst
The PHP link wasn't working as it was pointing to php-lang, but the actual URL is lang-php.
=> Update php url in guide_moodle.rst

source/guide_mailman-3.rst
Add an alternative configuration which does not rely on qmail (except for two minor options).
=> Update guide_mailman-3.rst - works (almost) without qmail

source/guide_the-lounge.rst
The Uberspace system's standard library is too old for the default pre-built binaries.
=> [thelounge] Add instructions to properly install SQLite

source/guide_homebox.rst
see title.
(although the project itself got archived but forks exist)
=> fix link in Homebox guide

source/guide_freshrss.rst
FreshRSS (now?) also allows updates via the web interface, which will automatically get the latest updates, without the need to manually download & replace the files. I've just done this on my space and it worked w/o problems. 
I've added that bit to the Upgrades section as an alternative.
=> add update method to FreshRSS

source/howto_automatic-deployment.rst
closes #1795 
This PR adds a guide on how to use `rrsync`` for restricting keys to only be able to write to allowed folders
=> [Automatic Deployment with CI/CD]  Secure rsync deployment

source/guide_actual.rst
Resolves #1802
Actual in its current version depends on a too new version of bcrypt not compatible with Uberspace v7. Can still be used by downgrading the bcrypt dependency.
=> fix actual guide, include bcrypt downgrade

README.md
It was previously ``guide`` but was then changed to ``new-guide``. The link still points to ``guide``.
=> Fix link to outdated label (README.md)

source/howto_automatic-deployment.rst
Adds mentions of the possible need for an SSH key passphrase to be provided to the rsync-deployments action if one's SSH key was protected by a passphrase upon creation.
Also add an explicit direction to use the "New repository secret/variable" buttons as the GitHub Actions secrets/variables pages nowadays also contain environment secrets/variables and so there's a little bit of an ambiguity as to which kind to use.
=> [howto_automatic-deployment] Mention the possible need for an SSH key passphrase

source/guide_beehive.rst
The guid for Beehive was missing a closing tag in the first note box.
=> Add missing closing tag

source/guide_firefly-iii.rst
Updated updates info to match the [official guide](https://docs.firefly-iii.org/how-to/firefly-iii/upgrade/self-managed/), because the "create-project" method is no longer recommended.
=> [firefly-iii] update updates info

README.md
enchant documentation [moved](https://github.com/AbiWord/enchant/commit/7e4d87ba2d2959dc0c3386ba53880f21e600cf1c) to a [new home](https://rrthomas.github.io/enchant/)
=> update enchant documentation link (fixes #1877)

source/howto_automatic-deployment.rst
Per https://github.com/Uberspace/lab/issues/1886
This PR suggests a small addition to the Automatic Deployment guide, the inclusion of an example of the `--exclude` rsync switch. I think this should be a recommended part of the workflow to prevent large, unneeded files such as the .git object from being included in the deploy.
=> [automatic-deployment] Enhance guide with notes about rsync exclusions

source/guide_datedmail.rst
I've created a new PowerShell module which restores the functionality of expiring mail addresses comparable to `qdated` which I previously used since U6.
This time the functionality is based on sieve filters and should be also be compliant to the upcoming U8, as qmail is not involved in any way.
=> Add guide for DatedMail

source/guide_wallabag.rst
The wallabag parameters.yml requires special characters to be url-encoded. This includes the smtp username, which for uberspace is <user>@<user-domain>, as well as any other strings in that file. Passwords for example.
See https://doc.wallabag.org/admin/mailer/
=> [wallabag] Updated guide: character url-encoding information added, small spelling mistake fixed

source/guide_goatcounter.rst
Remove a block about suggesting pip upgrade isso which looks as if it was copied from the isso page.
=> Remove copypaste leftover

source/guide_mosquitto.rst
Added a section on how to create configuration files for `mosquitto_pub` and `mosquitto_sub`. This way the mandatory arguments don't need to be provided every time the tools are executed, and they prevent leakage of credentials.
=> [Mosquitto] added client configuration files

source/guide_dendrite.rst
Update the upstream URL of Dendrite, which was moved to https://element-hq.github.io/dendrite/.
Fix commands to use the correct folder `~/dendrite` instead of `dendrite`.
Suggest database configuration to lower the amount of connections to reduce the resource consumption of PostgreSQL.
=> Add several updates to the Dendrite guide
